version: "3.9"
services:
  app:
    container_name: asobora_app
    build: ./docker/app
    volumes:
      - ./src:/data
    depends_on:
      - db
    networks:
      - app-network

  web:
    container_name: asobora_web
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  db:
    container_name: asobora_db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      TZ: Asia/Tokyo
    volumes:
      - db-store:/var/lib/postgresql/data
      # - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    name: asobora_network
    driver: bridge

# 名前付きボリュームの定義を追加
volumes:
  db-store:
  #   driver: local
